import os
import json
import time
import sqlite3
import uuid
import logging
from datetime import datetime, timedelta

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "axyntrax.db")
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "projects_output")

os.makedirs(OUTPUT_PATH, exist_ok=True)

logging.basicConfig(level=logging.INFO, format="[NEO-DEV] %(message)s")

class NeoDeveloper:
    """
    IA Orquestadora de Desarrollo Autónomo.
    Convierte items del catálogo en micro-acciones de scaffolding y despliegue simulado.
    """
    def __init__(self):
        pass

    def _get_connection(self):
        return sqlite3.connect(DB_PATH)

    def create_project(self, quote_data):
        """Crea un nuevo proyecto basado en un presupuesto aprobado."""
        proj_id = str(uuid.uuid4())[:8]
        name = f"Project_{quote_data['cliente']}".replace(" ", "_")
        folio = quote_data.get("folio", "N/A")
        deadline = (datetime.now() + timedelta(days=quote_data["financiero"]["eta_dias"])).isoformat()
        
        conn = self._get_connection()
        c = conn.cursor()
        c.execute(
            "INSERT INTO neo_projects (id, quote_folio, name, status, git_branch, deadline) VALUES (?, ?, ?, ?, ?, ?)",
            (proj_id, folio, name, "CREATED", f"feat/{proj_id}", deadline)
        )
        
        # Generar microtareas en cola
        for item in quote_data["conceptos"]:
            c.execute(
                "INSERT INTO task_queue (project_id, assigned_to, step_name, status, payload) VALUES (?, ?, ?, ?, ?)",
                (proj_id, "NEO", f"Scaffold {item}", "PENDING", json.dumps({"type": item}))
            )
        
        conn.commit()
        conn.close()
        logging.info(f"Proyecto {proj_id} ({name}) inicializado exitosamente.")
        return proj_id

    def run_cycle(self):
        """Busca tareas pendientes y las ejecuta."""
        conn = self._get_connection()
        c = conn.cursor()
        c.execute("SELECT id, project_id, step_name, payload FROM task_queue WHERE assigned_to = 'NEO' AND status = 'PENDING'")
        tasks = c.fetchall()
        conn.close()

        if not tasks:
            logging.info("No hay tareas pendientes para Neo.")
            return

        for task_id, proj_id, step, payload_str in tasks:
            logging.info(f"PROCESANDO: Task {task_id} para Proy {proj_id} -> {step}")
            
            # Simular ejecución de desarrollo
            time.sleep(1)
            payload = json.loads(payload_str)
            
            # Scaffold mock code
            self.scaffold_component(proj_id, step, payload)
            
            # Marcar completada
            conn2 = self._get_connection()
            c2 = conn2.cursor()
            c2.execute("UPDATE task_queue SET status = 'DONE', payload = ? WHERE id = ?", (json.dumps({"result": "SUCCESS", "time": datetime.now().isoformat()}), task_id))
            c2.execute("UPDATE neo_projects SET status = 'IN_PROGRESS' WHERE id = ?", (proj_id,))
            conn2.commit()
            conn2.close()
            logging.info(f"COMPLETADA: Task {task_id}.")
            
            # FASE DEEPSEEK: Sincronizar con el cerebro central
            self._sync_to_deepseek("TASK_COMPLETE", {
                "project_id": proj_id,
                "task": step,
                "status": "SUCCESS"
            })

    def _sync_to_deepseek(self, event_type, data):
        """Comunica eventos importantes al hub de conocimiento DeepSeek (Mock Cloud)."""
        import requests
        try:
            payload = {
                "agent": "NEO_DEV",
                "event_type": event_type,
                "payload": data
            }
            # En produccion llamará al supabase edge function
            logging.info(f"[DEEPSEEK-SYNC] Enviando bitácora a la nube estratégica: {event_type}")
            # requests.post("https://qatawtbfrfreakdbluat.supabase.co/functions/v1/deepseek_sync", json=payload, timeout=2)
        except Exception:
            pass

    def scaffold_component(self, proj_id, step, payload):
        """Simula la generación automática de código fuente."""
        proj_dir = os.path.join(OUTPUT_PATH, proj_id)
        os.makedirs(proj_dir, exist_ok=True)
        
        # Sanitize filename
        clean_step = "".join(c for c in step if c.isalnum() or c == ' ').replace(' ', '_')
        filename = f"{clean_step}.md"
        content = f"""# AUTOGENERATED BY NEO AI
        
## Component: {step}
Generated At: {datetime.now().isoformat()}
Project: {proj_id}

### Architecture: 
Modular component designed autonomously fitting requirements for: {payload.get('type', 'Generic Module')}

### Status:
[PASSED] Basic unit tests.
[PASSED] Syntax verification.
"""
        with open(os.path.join(proj_dir, filename), "w") as f:
            f.write(content)

if __name__ == "__main__":
    neo = NeoDeveloper()
    print("[NEO Agent] Iniciado en loop de prueba.")
    neo.run_cycle()
