import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import twofaRouter from "./twofa";
import usersRouter from "./users";
import clientsRouter from "./clients";
import licensesRouter from "./licenses";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import conversationsRouter from "./conversations";
import webhooksRouter from "./webhooks";
import gmailRouter from "./gmail";
import financesRouter from "./finances";
import paymentsRouter from "./payments";
import ceciliaRouter from "./cecilia";
import analyticsRouter from "./analytics";
import pushRouter from "./push";
import adminRouter from "./admin";
import modulesRouter from "./modules";
import portalRouter from "./portal";
import quotesRouter from "./quotes";
import salesBotRouter from "./sales-bot";
import securityRouter from "./security";
import moduleEventsRouter from "./module-events";
import moduleUpdatesRouter from "./module-updates";
import moduleSupportRouter from "./module-support";
import jarvisAdsRouter from "./jarvis-ads";
import jarvisLiveRouter from "./jarvis-live";
import tenantRouter from "./tenant";
import tenantCeciliaRouter from "./tenant-cecilia";
import tenantBusinessRouter from "./tenant-business";
import tenantWhatsappRouter from "./tenant-whatsapp";
import tenantBackupRouter from "./tenant-backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(twofaRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(licensesRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(conversationsRouter);
router.use(webhooksRouter);
router.use(gmailRouter);
router.use(financesRouter);
router.use(paymentsRouter);
router.use(ceciliaRouter);
router.use(analyticsRouter);
router.use(pushRouter);
router.use(adminRouter);
router.use(modulesRouter);
router.use(portalRouter);
router.use(quotesRouter);
router.use(salesBotRouter);
router.use(securityRouter);
router.use(moduleEventsRouter);
router.use(moduleUpdatesRouter);
router.use(moduleSupportRouter);
router.use(jarvisAdsRouter);
router.use(jarvisLiveRouter);
router.use(tenantRouter);
router.use(tenantCeciliaRouter);
router.use(tenantBusinessRouter);
router.use(tenantWhatsappRouter);
router.use(tenantBackupRouter);

export default router;
