-- Tabla de sincronización con DeepSeek
CREATE TABLE IF NOT EXISTS public.deepseek_sync (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Política RLS básica (solo el sistema puede escribir, lectura admin)
ALTER TABLE public.deepseek_sync ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas previas por si se re-ejecuta
DROP POLICY IF EXISTS "Solo admin puede leer sync" ON public.deepseek_sync;
DROP POLICY IF EXISTS "Sistema puede insertar sync" ON public.deepseek_sync;

CREATE POLICY "Solo admin puede leer sync"
  ON public.deepseek_sync FOR SELECT
  USING (auth.uid() = 'dd054e63-3d07-4431-b6ef-48d48526488b'); -- Admin ID real del CEO

CREATE POLICY "Sistema puede insertar sync"
  ON public.deepseek_sync FOR INSERT
  WITH CHECK (true); 

-- REFUERZO RLS ADICIONAL (SOLICITADO POR EL CEO)
-- Forzar lectura pública y escritura restringida en catálogos
ALTER TABLE public.modules_catalog ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura Publica Catalogo" ON public.modules_catalog;
CREATE POLICY "Lectura Publica Catalogo" ON public.modules_catalog FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admin Actualiza Catalogo" ON public.modules_catalog;
CREATE POLICY "Admin Actualiza Catalogo" ON public.modules_catalog FOR ALL USING (auth.uid() = 'dd054e63-3d07-4431-b6ef-48d48526488b');

ALTER TABLE public.gmail_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura Publica Templates" ON public.gmail_templates;
CREATE POLICY "Lectura Publica Templates" ON public.gmail_templates FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admin Actualiza Templates" ON public.gmail_templates;
CREATE POLICY "Admin Actualiza Templates" ON public.gmail_templates FOR ALL USING (auth.uid() = 'dd054e63-3d07-4431-b6ef-48d48526488b');
